[package]
name = "peach-buttons"
version = "0.1.0"
authors = ["Andrew Reid <gnomad@cryptolab.net>"]
edition = "2018"

[dependencies]
sysfs_gpio = "0.5.3"
jsonrpc-core = "11.0.0"
jsonrpc-ws-server = "11.0.0"
jsonrpc-pubsub = "11.0.0"
crossbeam-channel = "0.3"
